### ISSUE TITLE
trying to export GLTF my character but issue on blender 4.2

### ISSUE THREAD

**Issue by simplezywoo007** [ucupumar/ucup-export-helper#7]
little bug report 

Python: Traceback (most recent call last):
  File "C:\Users\kirig\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\ucup-export-helper-master\godot.py", line 516, in execute
    export_rig_ob = extract_export_rig(context, rig_object, scale, use_rigify, unparent_all=unparent_all)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kirig\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\ucup-export-helper-master\common.py", line 270, in extract_export_rig
    print(bone.name, bone.parent.name)
                     ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by agnira** [comment]
Hello, can you provide the configuration of your export options? I can't reproduce the error on my device.

**Comment by simplezywoo007** [comment]
![image](https://github.com/user-attachments/assets/a50cc3bc-156a-4473-929a-a87b986f5bd1)

**Comment by simplezywoo007** [comment]
[untitled.zip](https://github.com/user-attachments/files/17506189/untitled.zip)
here the blend file also

**Comment by agnira** [comment]
I can't access the zip file. :smile: 
![image](https://github.com/user-attachments/assets/cbcc6e93-af5e-4dd2-8d18-e187dcb247bd)
maybe it's too big?

**Comment by simplezywoo007** [comment]
it's weird upload get canceled all the time, maybe my internet connexion is so bad, do you have a email where i can send it

**Comment by agnira** [comment]
yeah, you can email me. rakai.sahakarya@gmail.com

**Comment by simplezywoo007** [comment]
[untitled.zip](https://github.com/user-attachments/files/17510341/untitled.zip)

**Comment by simplezywoo007** [comment]
anyway it's working now, sorry hahahahhaa

**Comment by agnira** [comment]
on check

**Comment by simplezywoo007** [comment]
> anyway it's working now, sorry hahahahhaa

i meant the zip file got upload here on github 
did you check the blend file inside 
is it working ?

**Comment by simplezywoo007** [comment]
https://github.com/user-attachments/files/17510341/untitled.zip

**Comment by agnira** [comment]
@Styl0o Yes, I can reproduce the error with your file. Unfortunately, I still don't have time to fix it, but hopefully, tomorrow or so.
@ucupumar misunderstood our conversation and closed the issue :laughing:  Sorry.
